### PR TITLE
Fix for Issue #10 - tgit.exe not found on windows 7 64bit

### PR DESCRIPTION
**Pull request by asfaltboy**
I just added a configurable path to tgit/git.exe file, with fallback to the old root path relative value.

### CODE REVIEW

**Comment by schlamar** [comment]
I can confirm this bug and the submitted patch.

**Comment by mikofski** [comment]
Please pull this, so that it works. I understand you want a better fix for this, but a broken package that users need to search for a patch to fix isn't better than waiting for a more elegant solution.

**Comment by brianhay-energetica** [comment]
I applied the patch but still no git context menu items. Changed path to correct "C:\Program Files (x86)\Git\bin\git.exe". Not  sure what I'm doing wrong. Win 7 64bit.

**Comment by livejamie** [comment]
This fix works.

@brianhay-energetica did you set it to

```
    "git_tgit_path": "C:\\Program Files (x86)\\Git\\bin\\git.exe",
```

JSON and regular expressions require backslashes to be escaped.

**Pull request closed without merging**
